### ISSUE TITLE
About 5-fold cross-validation

### ISSUE THREAD

**Issue by wanwan-na** [jcwang123/xboundformer#8]
May I ask whether it is necessary to test after 5-fold?

**Comment by wanwan-na** [comment]
> Could you please tell me whether the 5-fold cross-validation on the ISIC2018 data set is written in advance, and does it have the corresponding code?请问ISIC2018数据集上的5折交叉验证是否是提前写好的，有相应的代码吗？

**Comment by jcwang123** [comment]
The splitted ids have been stored in the "data_split.json".
        
    
        
            
        
    
                 
            
                font{
            line-height: 1.6;
        }-------------------------------------------font{
            line-height: 1.6;
        }Jiacheng Wang, PhD Student,Department of Computer Science at School of InformaticsXiamen University, Xiamen, ChinaHomepage: jcwang123.github.ioGoogle Scholar: ‪jiacheng wang
            
        
             
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/14/2023 21:43
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [jcwang123/xboundformer] About 5-fold cross-validation (Issue #8)
        
      
    
  


Could you please tell me whether the 5-fold cross-validation on the ISIC2018 data set is written in advance, and does it have the corresponding code?请问ISIC2018数据集上的5折交叉验证是否是提前写好的，有相应的代码吗？
